# Generated by Django 4.0 on 2022-01-08 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passesBoxOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passName', models.CharField(max_length=120)),
                ('passDescription', models.TextField()),
                ('passPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('passAvailability', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='passesSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTransaction', models.CharField(max_length=16)),
                ('account', models.CharField(max_length=4)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('customerName', models.CharField(max_length=255)),
                ('passName', models.CharField(max_length=120)),
                ('ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
    ]
