# Generated by Django 4.0 on 2022-01-06 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinyAccount', models.CharField(max_length=16)),
                ('originAccount', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('expDate', models.CharField(max_length=5)),
                ('ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('concept', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='transferStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionNum', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('origin', models.CharField(max_length=4)),
                ('destiny', models.CharField(max_length=4)),
            ],
        ),
    ]
